### ISSUE TITLE
Reproducible Research

### ISSUE THREAD

**Issue by katiejolly** [rladies-seattle/rladies-seattle-organizing#13]
# Topic

### Who is the audience?

* Researchers

* Students

* Anyone else interested in learning more about how to best structure projects that use R, although I'm hoping for the lessons to be applicable to other tools as well.

### Why is this important?

* Making research reproducible makes it easier for other people (or yourself in the future) to check your work and collaborate. 

### What should be covered?

* My idea is to have 3 or 4 different talks that range from beginner to advanced topics. Some ideas include:
- R projects/sessionInfo()
- Version control
- Docker
- Testing
- RMarkdown as a reproducibility tool
- renv/R package management
- makefiles

### Suggested speakers or contributors

TBD, going to ask around.

### Resources you would recommend to the audience

- https://monashdatafluency.github.io/r-rep-res/
- https://datacarpentry.org/rr-workshop/
- https://kbroman.org/Tools4RR/pages/resources.html
- https://annakrystalli.me/rrresearchACCE20/

**Comment by fuetra00** [comment]
Talk I could prepare, because I’m working on  this now - “Learning to make clear, compelling figures via reproducible code”

**Comment by fuetra00** [comment]
I’d show some really uninformative preliminary stuff I made, describe problems I had, how I approached fixing them, and why reproducible code simplified my life, and made me more confident in my work

**Comment by LiYingWang** [comment]
Hi! I'm very interested in giving a talk about reproducible research. The topic will be writing papers in R markdown that combines text and R code for data visualization and analysis, along with version control with git. I will be happy to demonstrate the workflow that I use for my papers, and how this workflow is practical and can be applied to many different types of research.

**Comment by katiejolly** [comment]
Hi @fuetra00 and @LiYingWang! Those both sound great. A few questions I have for you at this point:

1. Approximately how long do you think your presentation will be?
2. Does a lunchtime (let's say 12 or 12:30) meetup work for you? I have a slight preference for lunch because that makes it easier for later timezones to join as well. If not we can do something like 5:30 instead. 
3. Are there days during the week of Jan 11 that do not work for you? 
4. Is there anything I can do to help as you prepare your talk? 

Sometime before the end of the month please send me a bio, name you'd like me to use for you (ie nickname), gender pronouns, and a talk title & short description that I will use for marketing purposes and the meetup page. Thank you! 😄

**Comment by katiejolly** [comment]
I am also thinking about proposing a talk about makefiles/Docker with an example from my work. Still thinking about whether or not I want to volunteer for that though...

**Comment by kdillmcfarland** [comment]
I'd like to volunteer to teach Git or Rmarkdown, both of which I've taught before. No preference on which one.

**Comment by katiejolly** [comment]
@kdillmcfarland Sounds great! Let's go with talking about git and how it's useful specifically in the context of collaboration and reproducibility. Sometime in the next week or so please let me know:

1. Approximately how long do you think your presentation will be?
2. Does a lunchtime (let's say 12 or 12:30) meetup work for you? I have a slight preference for lunch because that makes it easier for later timezones to join as well. If not we can do something like 5:30 instead.
3. Are there days during the week of Jan 11 that do not work for you?
4. Is there anything I can do to help as you prepare your talk?
5. Would you be okay with your talk being recorded?

Additionally please send me a bio, name you'd like me to use for you (ie nickname), gender pronouns, and a talk title & short description that I will use for marketing purposes and the meetup page. Thank you! 😄

**Comment by katiejolly** [comment]
At this point with 3 confirmed talks we are probably set on speakers. However, I would say we can do shorter talks to fit 4 if someone else volunteers to talk about something that is not already covered by our current set. I think it would be great for someone to cover Docker but that also might be a good topic to have at a different event. And of course anyone who is interested can always do a talk at another event this year! 😄

**Comment by monicagerber** [comment]
@kdillmcfarland sounds like Git or R Markdown could be good workshop material. When you taught them before, how long did you need to teach these topics and what did you cover?  One idea is to give an intro talk or case study, and then dive into specifics in a follow-up workshop/tutorial later in the year if that's something you're willing to cover. I could help out with a workshop, especially if it uses materials from Data/Software Carpentry.

**Comment by monicagerber** [comment]
@katiejolly would love to attend a talk on Docker with extensive use analogies and illustrations. I have attended a few Docker talks and I still don't quite get it! Maybe if it was taught Carpentries-style where we code along with you?

**Comment by kdillmcfarland** [comment]
@monicagerber Yes! I've been discussing with Katie re: the time and style for this event. I'll be giving a short talk on git/GitHub. Happy to discuss a workshop-style event later in the year as well. I have 6 hrs of material (mix of my own and Carpentries) that covers reproducible research in R (projects, packrat, Rmd) and git (local, GitHub, interface in RStudio)

**Comment by LiYingWang** [comment]
@katiejolly Sounds great! I am excited that I can share my experiences. For your questions, my answers listed below:

1. I think my presentation will be 15-20 mins, but I can make it shorter or longer according to your schedule  
2. Lunchtime meetup or 5:30 all works for me
3. I am available that week except Jan 11 morning and Jan 15 morning
4. Is it possible to know audience type, such as novices or having some prior experiences? Also, for my presentation, my current thought is slide show for concepts, followed by a demonstration in R studio. Does it sound ok?
5. I am okay with recording

Also, how should I send you my bio and other information, by email or post here? Thank you!

**Comment by katiejolly** [comment]
@LiYingWang thank you! 15-20 min sounds perfect. 

For audience-- plan to have mostly people with some prior experience. You can expect that people will have used RMarkdown and are at least familiar with git (even if they haven't used it much). From what I can tell the range of experience is pretty wide which makes it a little difficult to plan for a specific level. Your proposed structure (concepts followed by demo) sounds great. Let me know ahead of time if you plan to have people follow along with you and I can note that in the event description! 

You can add your bio here or email me (katiejolly6@gmail.com), whichever one works best for you. Thank you again!! Looking forward to your talk!

**Comment by katiejolly** [comment]
@fuetra00 just checking in-- are you still planning to give a talk? Do you have any questions that I can help with? I think people would really enjoy hearing about your topic! 😄

**Comment by fuetra00** [comment]
Hi, yes, I am still interested.

Answers to your questions:
1. 15-20 minutes, whatever you need.
2. and 3. Lunch time all days that week OK.
4. I attended the meet up this week, so I have a sense of how things work.
5. OK with recording.

Tentative title: How reproducible code is helping me learn to make clearer,
more compelling figures.
Presentation: Slides with figures where I discuss how and why I change,
plus R studio script demo

Tracy

**Comment by katiejolly** [comment]
@fuetra00 Wonderful, thank you! 15-20 minutes is great 👍  Please feel free to let me know if any other questions come up as you're putting together your talk.

**Comment by katiejolly** [comment]
@fuetra00 @monicagerber @LiYingWang @kdillmcfarland 

Does 12:00 pst on Thurs Jan 14 work for all of you? I think yes based on what people have told me but just want to make sure I didn't miss something before schedule! Just trying to get most of this covered before people leave for holiday vacations 😄 Thumbs up this message if it works!

**Comment by fuetra00** [comment]
Yes, this date and time work for me!  

See you then. 

- tf

**Comment by katiejolly-ookla** [comment]
Hey everyone! Just made the event link https://www.meetup.com/rladies-seattle/events/275433771/. Please let me know if you would like for me to make any edits to the description or whatever else. And here's the poster if you'd like to share it. I'll start promoting the event more after the new year break. 
![rladies_jan_poster_twitter_draft](https://user-images.githubusercontent.com/56280392/103320755-7ab8b680-49eb-11eb-8583-16a94d32857a.png)

**Comment by LiYingWang** [comment]
@katiejolly-ookla Could I change the description of my talk to "Writing research papers with reproducible analysis using R Markdown compendia"? Thank you very much!

**Comment by katiejolly-ookla** [comment]
@LiYingWang Yep I will edit that now!

**Comment by katiejolly-ookla** [comment]
@LiYingWang @kdillmcfarland @fuetra00 

hey y'all! just wanted to check in. any last questions before the meetup on thursday? no need to respond if you don't have any 😄 and feel free to comment here anytime tomorrow/thursday morning if something comes up that i can help with!

**Comment by katiejolly-ookla** [comment]
@LiYingWang @kdillmcfarland @fuetra00 

THANK YOU THANK YOU to all the speakers!! I've gotten *such* positive feedback from everyone! The talks were excellent. If there's any feedback about what went well or what could be improved in the future please let me know!

**Comment by fuetra00** [comment]
I really enjoyed the other two presentations. Seeing other people's reproducible workflow was really helpful. Can someone send me the slack invite? I have a figshare repository. Not public yet, but will be eventually. Happy to share the link with R Ladies Seattle participants so they can play with my data and code

**Comment by monicagerber** [comment]
@fuetra00 send us an email at seattle@rladies.org with the email address you'd like to use to access Slack.

**Comment by LiYingWang** [comment]
Thank @katiejolly-ookla and @monicagerber for organizing the workshop! It was really great to share and learn from the other two presentations. Could you also send me the slack invitation using this email address: jaybin502@gmail.com? I would like to share the packages I use for making tables there. Thank you very much!
