### ISSUE TITLE
How to give a good conference or meetup talk

### ISSUE THREAD

**Issue by monicagerber** [rladies-seattle/rladies-seattle-organizing#16]
# Topic

### Who is the audience?
All R-Ladies members
Could invite folks from other Seattle data science meet-ups

### Why is this important?
Help more people see themselves as experts and speakers

### What should be covered?
-How to give lightning talk
-How to give a longer talk
-Online vs. in-person considerations 
- List of data science conferences to look out for in upcoming year
- R-Ladies speaker directory

### Suggested speakers or contributors
- @rctatman gave a previous talk on how to give a lightning talk -- could she give again or recommend someone who has given a great lightning talk?
- @mariev, @k8hertweck, @karawoo all gave talks at rstudio::global and may have some good tips or suggestions for this event.

### Resources you would recommend to the audience
- R-Ladies speaker directory
- [Demystifying Public Speaking](https://abookapart.com/products/demystifying-public-speaking)
- Could come up with list of great online talks

**Comment by k8hertweck** [comment]
I'd be happy to contribute to this discussion! I have a blog post on my to-do list that does a debriefing of my rstudio::global experience preparing a talk.

**Comment by karawoo** [comment]
I'd be happy to join in as well

**Comment by mariev** [comment]
happy to! I think my experience with RStudio was a bit different due to format.

**Comment by monicagerber** [comment]
Thanks @k8hertweck, @karawoo, and @mariev! Some follow-up questions:

- What do you think is the best format for this? Do you each want to do a short presentation (up to 20 min)? 
- Is there anything in the "what should be covered?" section that you'd like to take on? Something I missed? 

For this event, I'd like to utilize a collaborative document so that attendees can help us crowd source info on events that are coming up in the next year and talk proposal deadlines.

I'd like to aim for an evening in early March. Will follow-up with you via email for scheduling.

**Comment by karawoo** [comment]
I am, ironically, not developing any new presentations right now (I'm still recovering from giving three brand new talks within a ten day period and I told myself I'd cool it for a while). I'd be happy to participate in a more panel-style discussion, or if others are interested in giving presentations then I'm happy to sit back and chime in during the q&a.

**Comment by k8hertweck** [comment]
I like the idea of a panel discussion, because it's pretty fun to talk about different styles of preparing talks, and can offer a diversity of options for the audience to consider side-by-side. We could have a short presentation at the beginning that can provide an overview of basic topics/resources?

**Comment by stefaniebutland** [comment]
Resource: [Some handy guidelines on giving a lightning talk](https://github.com/tracykteal/lightning-talks), by Tracy Teal

**Comment by monicagerber** [comment]
Meet-up scheduled for Wednesday, April 7th at 6pm. Thanks @ivelasq for moderating! 

https://www.meetup.com/rladies-seattle/events/276427163/
