### ISSUE TITLE
Create a new banner for the meetup.com page utilizing the R-Ladies Seattle logo

### ISSUE THREAD

**Issue by monicagerber** [rladies-seattle/rladies-seattle-organizing#17]
Request for a volunteer with design skills or aspiration!

Change the main page photo here: https://www.meetup.com/rladies-seattle

**Comment by ivelasq** [comment]
Throwing an option into the ring :)
![cover](https://user-images.githubusercontent.com/12236152/108284520-fe209980-714a-11eb-8346-7b973c302302.png)

**Comment by monicagerber** [comment]
OMG THIS LOOKS AMAZING!

**Comment by monicagerber** [comment]
I saved this to the Branding/ directory in our shared Google Drive and updated our meetup.com page. Thanks Isabella :)
I love it!
