### ISSUE TITLE
In the Outdoors with R-Ladies Seattle

### ISSUE THREAD

**Issue by monicagerber** [rladies-seattle/rladies-seattle-organizing#18]
# Topic

⛺ 🌴 🛹 🧗‍♀️  Lightning talks on analyses/packages/etc. that are outdoors-themed.

### Who is the audience?
All of the R-Ladies members who are into kayaking, climbing, biking, city walks, birding, skiing, and commuting to work via a paddle board across Lake Union. 

### Why is this important?
It's Seattle -- we're outdoorsy! And it will be fun. 

### What should be covered?
5 min lightning talks

### Suggested speakers or contributors
Me!
Jessica Dyer did an analysis of avalanche data (we should invite NWAC if she presents)

If you want to present, give this a 🚀 and I will be sure to notify you once it is scheduled. Also feel free to comment with questions/ideas.
If you like this idea, give me a 👍 !

### Resources you would recommend to the audience
@ivelasq gave a talk a while back on her analysis of [hiking data](https://docs.google.com/presentation/d/1hDxK7gbdg13HzeIGQ9Od-tCHhOwfKM1fSCoeJpvjlaA/edit#slide=id.p).
Rachael Tatman's [guide to giving a lightning talk](https://docs.google.com/presentation/d/1nod6zgs1DQczpxWg_8opKS7gDmzWMmjMNWIxKzjhEWM/edit).

**Comment by golden-frog-JB** [comment]
I would like to give a presentation on recreation (camping/fishing) data and common pitfalls!

**Comment by kdillmcfarland** [comment]
Completed 4/20/23
https://www.meetup.com/rladies-seattle/events/292697592/
