### ISSUE TITLE
Writing slides with R-based tools

### ISSUE THREAD

**Issue by katiejolly-ookla** [rladies-seattle/rladies-seattle-organizing#19]
# Topic

Packages like `{xaringan}` provide a nice framework for drafting slides with (R)markdown. In preparation for April's "how to give a good talk" meetup we will talk about the logistics of putting together the slides!

### Who is the audience?

* R users interested in giving talks and/or using Rmarkdown to write those talks

### Why is this important?

* writing your slides directly in rmarkdown makes it easy to include analysis, charts, and data directly into your presentations to make them reproducible! Using xaringan also allows for a wide degree of customization while also providing really nice defaults. 

### What should be covered?

* writing xaringan slides
* deploying xaringan slides
* learnr (maybe as an alternative presentation tool)

### Suggested speakers or contributors

* [Silvia Canelón](https://silvia.rbind.io/talk/2020-11-03-xaringan-basics-and-beyond/) has given a longer workshop on xaringan and has offered to do a shorter presentation for this audience

### Resources you would recommend to the audience

* https://bookdown.org/yihui/rmarkdown/xaringan.html
* https://annakrystalli.me/talks/xaringan/xaringan.html#1

**Comment by mcsiple** [comment]
For the `xaringan` part of this session, I'd love to talk about best / easiest practices for sharing our slides- through github pages, Netlify, or other ways that people prefer. Personally I've had some trouble sharing slides via github pages, though I *have* done it before. I would love to dig into this and learn by presenting but I am more slammed than usual at work right now. 

Maybe if there's time we can also talk about [xaringanthemer](https://pkg.garrickadenbuie.com/xaringanthemer/) for getting/modifying themes too.

**Comment by katiejolly-ookla** [comment]
I think these are both great ideas! I could take on one of them and I'll chat with Silvia to see if she's planning to cover either one. Ideally maybe we can find someone newer to presenting :) I'll ask around!

**Comment by spcanelon** [comment]
> I think these are both great ideas! I could take on one of them and I'll chat with Silvia to see if she's planning to cover either one. Ideally maybe we can find someone newer to presenting :) I'll ask around! 

I don't use xaringanthemer myself so I'm happy to cover slide deployment. Thanks for the suggestion @mcsiple!

Maybe half of the demo can cover basics of xaringan and the other half slide deployment via GitHub pages.

**Comment by katiejolly-ookla** [comment]
@spcanelon That sounds good to me! I will ask around specifically for people who know xaringanthemer. I use it for most of my presentations so can always do it if we don't get any other volunteers.

**Comment by kmasiello** [comment]
I deploy ‘xaringan’ slides as part of embedded content on ‘distill’ sites. I can help cover this topic if interested. Example here: https://kmasiello.github.io/why_apis/

**Comment by spcanelon** [comment]
The sharing and embedding features of the `xaringanExtra` package are definitely super handy for embedding slides into a distill or blogdown site! I'll defer to @katiejolly-ookla but I think demo-ing `xaringanExtra` and building a distill site may require more time than what was in mind for the meetup 🤔 

To clarify, I was thinking to demo deployment via GitHub pages to show people how to obtain a direct and shareable link to the slide deck regardless of whether they want to embed their slides somewhere.

For example:
- This link is generated directly from my [GitHub repo](https://github.com/spcanelon/tour-of-the-tidyverse) via GitHub pages: https://spcanelon.github.io/tour-of-the-tidyverse/index.html
- And I used that link to embed my slides in my [blogdown site](https://silvia.rbind.io/talk/2020-08-31-tour-of-the-tidyverse/)

**Comment by katiejolly-ookla** [comment]
It seems like there's a ton of interest in all the xaringan features! And probably more than we can meaningfully cover in one meetup. For now let's plan to stick to just the basic design and deployment but @kmasiello you're on my list of people to reach out to for cool slide things in the future 😄 And we will be putting together resource lists for attendees so this will be a great thing to include on that list! 

Fwiw I think covering distill at some point would also be a good topic.

**Comment by katiejolly-ookla** [comment]
Okay so for right now let's plan on having Silvia's longer talk. Silvia-- we can chat about what to include exactly. Some deployment would be great but feel free to take some creative liberty! I'll plan to give more of a lightning talk style demo of xaringanthemer unless someone else volunteers for that. 

I'll plan on Tues March 16, 5:30-6:30pm!

**Comment by mcsiple** [comment]
Woohoo @spcanelon and @kmasiello -- this is exactly what I want to move towards. So far I have only ever deployed standalone slides through github pages and I still don't have a great workflow for it. I like the idea of doing a `xaringan`-focused meetup where we talk about standalone slides w github page deployment, then a later meetup focused on `distill` for which deploying `xaringan` slides is one of the features. I'm so glad my fellow R-Ladies are skilled at these things! This is great.

**Comment by katiejolly-ookla** [comment]
I will make the meetup event today or tomorrow and post the link here when I do. Ty for all the planning help, everyone! 💜

**Comment by katiejolly-ookla** [comment]
Meetup link: https://www.meetup.com/rladies-seattle/events/276570832

And the event image 
![twitter_img_march](https://user-images.githubusercontent.com/56280392/109083181-45160e00-76ba-11eb-8d51-f305cfadb061.png)

Let me know if anyone wants an edit to any of it!

cc @spcanelon

**Comment by spcanelon** [comment]
This looks beautiful! And the content looks great to me 👍

**Comment by katiejolly-ookla** [comment]
@spcanelon just want to reach out real quick-- any last questions, etc. I can help with? I'm looking forward to the meetup this evening!

We've already seen some requests for materials from your talk, as a heads up 😄 If you're comfortable sharing then I can post in the meetup event after the event ends.

**Comment by spcanelon** [comment]
Hi @katiejolly-ookla! No questions here and I'm looking forward to the meetup too!

Yes, definitely comfortable sharing the materials. I'm finalizing the accompanying blog post right now but I'll be linking it here: https://silvia.rbind.io/talk/2021-03-16-xaringan-deploy-demo/

**Comment by mcsiple** [comment]
This looks so amazing @spcanelon ! Thank you for putting all this work into this presentation and materials... also it looks much more painless than my `xaringan` experience to date.

**Comment by spcanelon** [comment]
Thank you @mcsiple!! And I'm so glad to hear the deployment process looks more approachable now, hopefully the demo will confirm!
