### ISSUE TITLE
BoF at Cascadia R Conference

### ISSUE THREAD

**Issue by mariev** [rladies-seattle/rladies-seattle-organizing#20]
# Topic
ASA JEDI initiative

### Who is the audience?
Cascadia R Conference, June 4-5

### Why is this important?
Background: https://magazine.amstat.org/blog/2020/10/01/jedi/

### What should be covered?
Updates and open floor discussion

### Suggested speakers or contributors

Erin Chapman, ASA JEDI committee member, https://www.linkedin.com/in/erin-e-chapman

### Format
~20 minute BoF forum at Cascadia R Conference

**Comment by monicagerber** [comment]
Thanks for suggesting this, Marie. 

When I attended an in-person BoF session at rstudio::conf, it was informal networking. What are you imagining the format would be for this BoF? It looks like you are suggesting that Erin Chapman give updates on this ASA initiative followed but some kind of discussion.

How would you like R-Ladies Seattle to be involved?

**Comment by monicagerber** [comment]
R-Ladies Seattle members have offered to help support this event and give input, but will not be co-hosting it.
