### ISSUE TITLE
Create an app for Slack sign-up

### ISSUE THREAD

**Issue by monicagerber** [rladies-seattle/rladies-seattle-organizing#23]
Create something similar to the global org app: https://rladies-community-slack.herokuapp.com/

**Comment by monkeywithacupcake** [comment]
do we have access to the global org code? Because it is mostly a pamphlet....so, that could save a lot of copy/pasting

**Comment by kdillmcfarland** [comment]
I volunteer as tribute

**Comment by kdillmcfarland** [comment]
Done!
https://github.com/rladies-seattle/blogdown_site/pull/14
